### ISSUE TITLE
The text field icon should be also gray in SVG, like in the standard icon in text field

### ISSUE THREAD

**Issue by ofekashery** [trimox/angular-mdc-web#1633]
### What Angular MDC version are you using?
v0.42.1

![image](https://user-images.githubusercontent.com/16443111/50535780-2fe2da80-0b56-11e9-8c68-e1366c138988.png)

**Comment by trimox** [comment]
@ofekashery Use of SVG inside `mdc-text-field` is not officially supported _yet_, there is an open issue to add full support.

In the meantime, use the following Sass to achieve a gray SVG icon inside `mdc-text-field`.

```scss
.mdc-text-field:not(.mdc-text-field--disabled) .mdc-text-field__icon {
  fill: rgba(0, 0, 0, 0.54);
}
```
