### ISSUE TITLE
Can't use mdc mixins

### ISSUE THREAD

**Issue by gpulido** [trimox/angular-mdc-web#1849]
**Describe the bug**
I configured an angular app following the Getting Started guide and every time I try to import a mdc mixin on a scss it can't be found with a 
```
no mixin named mdc-button-container-fill-color
```

One example is just trying to add a button related mixin to the example:
https://stackblitz.com/edit/angular-mdc-s1rusl?file=src%2Fapp%2Fapp.component.scss

**What Angular MDC version are you using?**
0.44.0

**Additional context**
Maybe I haven't configured something to make it work, but I just have followed the getting started guide.

**Comment by trimox** [comment]
@gpulido Try this instead.

In `styles.scss`
```scss
$mdc-theme-primary: #6200ee;
$mdc-theme-secondary: #faab1a;

@import "~@angular-mdc/theme/material";

.demo-custom {
  @include mdc-button-container-fill-color(green);
}
```

In `app.component.ts`
```ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent  {
}
```

In `app.component.html`
```html
<button class="demo-custom" mdc-button raised>My Button</button>
```

And finally, remove `app.component.scss`.
