### ISSUE TITLE
scroll on open menu

### ISSUE THREAD

**Issue by rui-cruz** [trimox/angular-mdc-web#306]
Before all, thank you very much for the select component!

I notice that, when you have a selected item, and you open the menu, and then scroll, the menu closes, but the selected item stays hidden.

This scrolling option is great, you should also implement on the component menu!

Thank you again!

**Comment by trimox** [comment]
Very much appreciated!
I noticed this issue once during design, but couldn't duplicate. Thanks for the steps to reproduce, I'll take a look.

**Comment by Eski** [comment]
Hi, 

Very nice component, thx again, but i struggle to make the mdc-select and mdc-select-items have full width of parent container.

**Comment by trimox** [comment]
@Eski I'll update the documentation with a better approach but here's a quick and dirty..
```css
.select-container {
  width: 200px;

  .mdc-select {
    width: inherit;
  }

  .mdc-select__menu {
    width: inherit;
  }
}
```
